export const ROUTE = {
  onBoarding: "/",
  login: "/login",
  notFound: "/404",
  home: "/home",
  wishlist: "/wishlist",
  search: "/search",
  mostPopular: "/most-popular",
  cart: "/cart",
  orders: "/orders",
  checkout: "/checkout",
  payment: "/payment-method",
  shippingAddress: "/shipping-address",
  shippingMethod: "/shipping-method",
};
